name: Ensure code quality
on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/prepare
            - name: Lint code
              run: |
                  pnpm run lint

    check-format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/prepare
            - name: Check code format
              run: |
                  pnpm run format:check

    try-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/prepare
            - name: Try build
              run: |
                  pnpm run build:check

    test:
        runs-on: ubuntu-latest
        needs: [try-build]
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/prepare
            - name: Run tests
              run: |
                  pnpm run test:coverage --watch=false

